from pydantic import BaseModel, Field


class ActionItem(BaseModel):
    task: str = Field(
        description="Task to be completed."
    )

    assignee: str | None = Field(
        default=None,
        description="Person responsible."
    )

    deadline: str | None = Field(
        default=None,
        description="Deadline if mentioned."
    )


class MeetingChunkAnalysis(BaseModel):
    """
    Analysis of a single transcript chunk.
    Generated by the Map Chain.
    """

    summary: str = Field(
        description="Concise summary of this transcript chunk."
    )

    topics: list[str] = Field(
        default_factory=list,
        description="Topics discussed."
    )

    decisions: list[str] = Field(
        default_factory=list,
        description="Decisions made."
    )

    action_items: list[ActionItem] = Field(
        default_factory=list
    )

    questions: list[str] = Field(
        default_factory=list,
        description="Questions raised."
    )

    risks: list[str] = Field(
        default_factory=list,
        description="Risks, blockers or concerns."
    )

    deadlines: list[str] = Field(
        default_factory=list,
        description="Deadlines mentioned."
    )

    important_points: list[str] = Field(
        default_factory=list,
        description="Important facts."
    )

    participants: list[str] = Field(
        default_factory=list,
        description="People mentioned."
    )


class MeetingReport(BaseModel):
    """
    Final meeting report generated by the Reduce Chain.
    """

    title: str

    executive_summary: str

    meeting_purpose: str

    discussion_topics: list[str]

    key_decisions: list[str]

    action_items: list[ActionItem]

    open_questions: list[str]

    risks_and_blockers: list[str]

    deadlines: list[str]

    follow_up_items: list[str]

    key_takeaways: list[str]

    next_meeting: str

    keywords: list[str]

    timeline: list[str]

    final_conclusion: str
